# Generated by Django 5.1.1 on 2026-05-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta de Productos'), ('atencion', 'Atención Médica / Servicio')], default='venta', max_length=20),
        ),
    ]
