# Generated by Django 5.1.1 on 2026-05-04 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiales', '0001_initial'),
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mascotas.mascota'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='historiales.historialclinico'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='historiales.historialclinico'),
        ),
    ]
