# Generated by Django 5.1.1 on 2026-05-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desparasitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], max_length=10)),
                ('producto', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones', to='mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascotas.mascota')),
            ],
        ),
    ]
